import {createSelection,nextQuestion,submitChoice,selectionAudit} from './selection-engine.js?v=2';
const $=id=>document.getElementById(id),KEY='blind-face-select-v2';
const phases={preliminary:'PRELIMINARY',main:'MAIN ROUND',late:'LATE ROUND',recovery:'BORDERLINE RECHECK',boundary:'TOP9 BORDERLINE',rank:'DIRECT COMPARISON'};
let db=read(),catalog=null,player=null,session=null,question=null,picks=new Set(),previous=null,revealed=0;
function read(){try{const data=JSON.parse(localStorage.getItem(KEY));return data&&Array.isArray(data.players)&&data.sessions?data:{players:[],sessions:{}}}catch{return {players:[],sessions:{}}}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function visible(id){for(const section of document.querySelectorAll('main>section'))section.hidden=section.id!==id;window.scrollTo(0,0)}
function openCatalog(){return new Promise((resolve,reject)=>{const req=indexedDB.open('blind-face-select-assets',1);req.onupgradeneeded=()=>req.result.createObjectStore('catalogs');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const d=req.result,t=d.transaction('catalogs','readonly'),g=t.objectStore('catalogs').get('active');g.onsuccess=()=>resolve(g.result);g.onerror=()=>reject(g.error);t.oncomplete=()=>d.close()}})}
function normalize(c){return {id:c.candidate_id||c.id,name:c.display_name||c.name,group:c.group||c.affiliation||'',imageUrl:c.image_source_url||c.imageUrl,sourceUrl:c.official_profile_url||c.sourceProfileUrl,imageStatus:c.image_status||'unverified'}}
function validCatalog(d){if(!d||!Array.isArray(d.candidates)||d.candidates.length<9||d.candidates.length>150)return false;const c=d.candidates.map(normalize);return c.every(x=>x.id&&x.name&&x.imageUrl?.startsWith('https://')&&x.sourceUrl?.startsWith('https://'))&&new Set(c.map(x=>x.id)).size===c.length}
openCatalog().then(d=>{if(validCatalog(d)){catalog={version:d.version,candidates:d.candidates.map(normalize)};const opt=$('set').options[1];opt.disabled=false;opt.textContent=`端末内の写真カタログ（${catalog.candidates.length}人）`;$('catalogMessage').textContent=`候補セット：${catalog.version}。写真は公式サイトのURLから表示します。`}else $('catalogMessage').textContent='写真カタログは未設定です。架空IDで操作試験ができます。'}).catch(()=>$('catalogMessage').textContent='端末内カタログを読み込めません。');
function refreshPlayers(){const select=$('playerList'),current=select.value;select.replaceChildren(new Option('新しいプレイヤー',''));for(const p of db.players)select.add(new Option(p.nickname||'名前なし',p.id));select.value=current;if(!select.value)select.value='';select.onchange=()=>{const p=db.players.find(x=>x.id===select.value);$('nickname').value=p?.nickname||'';$('age').value=p?.age||'';$('nickname').disabled=!!p;$('age').disabled=!!p;$('resume').hidden=!p||!db.sessions[p.id]||db.sessions[p.id].state.phase==='complete';$('past').hidden=!p||!db.sessions[p.id]||db.sessions[p.id].state.phase!=='complete'};select.onchange()}
function selectedPlayer(){const id=$('playerList').value;if(id)return db.players.find(p=>p.id===id);const p={id:crypto.randomUUID(),nickname:$('nickname').value.trim(),age:$('age').value,createdAt:new Date().toISOString()};db.players.push(p);$('playerList').value=p.id;return p}
function persist(){session.updatedAt=new Date().toISOString();db.sessions[player.id]=session;save()}
function begin(){player=selectedPlayer();const type=$('set').value;if(type==='catalog'&&!catalog){$('catalogMessage').textContent='カタログの読み込み完了を待ってください。';return}const candidates=type==='catalog'?catalog.candidates:Array.from({length:140},(_,i)=>({id:'demo-'+String(i+1).padStart(3,'0'),name:'架空候補 '+String(i+1).padStart(3,'0'),group:'操作試験',imageUrl:null,sourceUrl:null}));session={playerId:player.id,setVersion:type==='catalog'?catalog.version:'demo-140-v2',type,candidates,state:createSelection(candidates.map(c=>c.id),{lateSize:3}),createdAt:new Date().toISOString(),completedAt:null};previous=null;persist();renderQuestion()}
function resume(){player=db.players.find(p=>p.id===$('playerList').value);session=db.sessions[player.id];previous=null;if(session.state.phase==='complete')showResult();else renderQuestion()}
function blindMap(){const ids=session.candidates.map(c=>c.id);return new Map(ids.map((id,i)=>[id,'FACE '+String(i+1).padStart(3,'0')]))}
function renderQuestion(){question=nextQuestion(session.state);picks=new Set();if(!question){session.completedAt=session.completedAt||new Date().toISOString();persist();revealed=0;showResult();return}persist();visible('game');$('phase').textContent=phases[question.phase];$('instruction').textContent=question.phase==='rank'||question.phase==='boundary'?'より好みの顔を1人選択':`${question.ids.length}人から${question.max}人まで選択`;$('progress').textContent=`${session.state.history.length+1}画面目｜最大${question.max}人`;$('uncertain').checked=false;$('faces').replaceChildren();const byId=new Map(session.candidates.map(c=>[c.id,c])),labels=blindMap();for(const id of question.ids){const c=byId.get(id),b=document.createElement('button');b.className='face';b.type='button';b.dataset.id=id;b.setAttribute('aria-pressed','false');b.setAttribute('aria-label','顔画像 '+labels.get(id));if(c?.imageUrl){const img=document.createElement('img');img.src=c.imageUrl;img.alt='';img.onerror=()=>{b.disabled=true;b.replaceChildren(document.createTextNode('画像を表示できません'));$('gameStatus').textContent='表示できない写真があります。選考を中断し、カタログの画像URLを確認してください。';$('next').disabled=true};b.append(img)}else b.textContent=labels.get(id);b.onclick=()=>{if(b.disabled)return;if(picks.has(id))picks.delete(id);else if(picks.size<question.max)picks.add(id);for(const el of $('faces').children)el.setAttribute('aria-pressed',String(picks.has(el.dataset.id)));$('next').disabled=picks.size<question.min||[...$('faces').children].some(el=>el.disabled);$('gameStatus').textContent=`${picks.size}人を選択中`};$('faces').append(b)}$('gameStatus').textContent='0人を選択中';$('next').disabled=true;$('undo').disabled=!previous}
function card(c,rank){const box=document.createElement('article');box.className='rank';const title=document.createElement('strong');title.textContent=rank+'位';box.append(title);if(c?.imageUrl){const image=document.createElement('img');image.src=c.imageUrl;image.alt='';image.onerror=()=>image.replaceWith(Object.assign(document.createElement('div'),{className:'placeholder',textContent:'画像を表示できません'}));box.append(image)}else{const dummy=document.createElement('div');dummy.className='placeholder';dummy.textContent='画像なし';box.append(dummy)}const name=document.createElement('h3');name.textContent=c?.name||'架空候補';box.append(name);const group=document.createElement('p');group.textContent=c?.group||'';box.append(group);if(c?.sourceUrl){const a=document.createElement('a');a.href=c.sourceUrl;a.target='_blank';a.rel='noopener noreferrer';a.textContent='公式Source';box.append(a)}return box}
function showResult(){visible('result');$('analysis').hidden=true;$('reveal').hidden=false;$('ranking').replaceChildren();$('resultInfo').textContent=`${session.candidates.length}候補／${session.state.history.length}画面。9位から順に本人情報を表示します。`;renderReveal()}
function renderReveal(){const ids=[...session.state.ranking].reverse(),byId=new Map(session.candidates.map(c=>[c.id,c]));$('ranking').replaceChildren();for(let i=0;i<9;i++){if(i<revealed)$('ranking').append(card(byId.get(ids[i]),9-i));else{const div=document.createElement('div');div.className='rank';div.textContent=`${9-i}位　未公開`;$('ranking').append(div)}}$('reveal').textContent=revealed===9?'Reveal完了':`${9-revealed}位を Reveal`;if(revealed===9){$('reveal').hidden=true;$('analysis').hidden=false;renderAnalysis()}}
function renderAnalysis(){const audit=selectionAudit(session.state),byId=new Map(session.candidates.map(c=>[c.id,c]));const host=$('analysisBody');host.replaceChildren();const overview=document.createElement('p');overview.textContent=`選択画面：${audit.screens}／迷った比較：${audit.uncertainComparisons}／境界再比較：${audit.borderlineComparisons}。集計は選択行動だけを示し、顔の特徴を自動推定しません。`;host.append(overview);const table=document.createElement('table');table.className='stats';const head=document.createElement('tr');for(const label of ['順位','候補','選択','非選択','再登場','経路']){const th=document.createElement('th');th.textContent=label;head.append(th)}table.append(head);for(const [i,id] of session.state.ranking.entries()){const shown=session.state.history.filter(h=>h.shown.includes(id));const wins=shown.filter(h=>h.chosen.includes(id)).length;const tr=document.createElement('tr');for(const value of [i+1,byId.get(id)?.name||'架空候補',wins,shown.length-wins,Math.max(0,shown.length-1),[...new Set(shown.map(h=>phases[h.phase]))].join(' → ')]){const td=document.createElement('td');td.textContent=value;tr.append(td)}table.append(tr)}host.append(table);const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='全比較履歴を表示';details.append(summary);const list=document.createElement('ol');for(const h of session.state.history){const li=document.createElement('li');li.textContent=`${phases[h.phase]}：表示 ${h.shown.map(id=>byId.get(id)?.name||id).join('／')} → 選択 ${h.chosen.map(id=>byId.get(id)?.name||id).join('／')}${h.uncertain?'（迷った）':''}`;list.append(li)}details.append(list);host.append(details)}
function encode(data){const bytes=new TextEncoder().encode(JSON.stringify(data));let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function decode(s){const bytes=Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
function shared(){if(!location.hash.startsWith('#share='))return false;visible('shared');try{const data=decode(location.hash.slice(7));if(!Number.isFinite(data.expiresAt)||Date.now()>data.expiresAt){$('sharedStatus').textContent='この共有リンクの有効期限は終了しました。';return true}if(!Array.isArray(data.ranking)||data.ranking.length!==9)throw Error('invalid');$('sharedStatus').textContent=`有効期限：${new Date(data.expiresAt).toLocaleString('ja-JP')}／候補セット：${data.version}`;for(const [i,c] of data.ranking.entries())$('sharedRanking').append(card(c,i+1))}catch{$('sharedStatus').textContent='共有URLを読み取れませんでした。'}return true}
$('begin').onclick=begin;$('resume').onclick=resume;$('past').onclick=resume;$('next').onclick=()=>{if(picks.size<question.min||[...$('faces').children].some(el=>el.disabled))return;previous=JSON.stringify(session.state);submitChoice(session.state,[...picks],{uncertain:$('uncertain').checked});persist();renderQuestion()};$('undo').onclick=()=>{if(previous){session.state=JSON.parse(previous);previous=null;persist();renderQuestion()}};$('leave').onclick=()=>{persist();refreshPlayers();$('playerList').value=player.id;$('playerList').onchange();visible('setup')};$('reveal').onclick=()=>{if(revealed<9)revealed++;renderReveal()};$('resultHome').onclick=()=>{refreshPlayers();$('playerList').value=player.id;$('playerList').onchange();visible('setup')};$('expiry').onchange=()=>$('customWrap').hidden=$('expiry').value!=='custom';$('makeShare').onclick=()=>{const hours=$('expiry').value==='custom'?Number($('customHours').value):Number($('expiry').value);if(!Number.isFinite(hours)||hours<1||hours>720){$('shareStatus').textContent='1〜720時間で指定してください。';return}const byId=new Map(session.candidates.map(c=>[c.id,c]));const ranking=session.state.ranking.map(id=>{const c=byId.get(id);return {name:c.name,group:c.group,imageUrl:c.imageUrl,sourceUrl:c.sourceUrl}});const url=new URL(location.href);url.hash='share='+encode({expiresAt:Date.now()+hours*3600000,version:session.setVersion,ranking});$('shareLink').hidden=false;$('shareLink').value=url.href;$('shareStatus').textContent='共有URLを作成しました。コピーして送れます。'};
refreshPlayers();if(!shared())visible('setup');
